baseurl: https://memoreal.co/
title: Maximillian, Geriant, Chloe & Chris
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: '&copy;2021 Bo'
  description: Bo's family
  email: ckris@163.com
  navlinks:
    - home: yes
      name: Home
      url: portfolio/
    - name: About
      url: about/
    - name: Blog
      url: post/
    - name: Gallery
      url: gallery/
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - I am a data scientist dedicated to data science for the greater good and the whole society with 10+ years of toG, toC
and toB experiences in product-grade software development and real-world AI problems. I also have a lovely family.
    - Originally from Beijing, currently based in Beijing.
  social:
    email: ckris@163.com
    facebook: full page or profile url in facebook
    github: full profile url in github
    instagram: full profile url in instagram
    linkedin: full profile url in linkedin
    twitter: full profile url in twitter
    whatsapp: wa.me service link
    youtube: full profile url in youtube
  style: default
